sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo g # generate static files

after_script:
  - cd ./public
  - git init
  - git config user.name "will"
  - git config user.email "641631209@11.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/wsh0809/wsh0809.github.io" gh-pages:gh-pages
